FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest

RUN dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes python3 python3-dev python3-pip python3-setuptools python3-wheel